services:

  In2code\Luxletter\:
    resource: '../Classes/*'

  In2code\Luxletter\Widget\OpenRateWidget:
    arguments: ['luxletterOpenRate']
    tags:
      - name: dashboard.widget
        identifier: luxletterOpenRate
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\ClickRateWidget:
    arguments: ['luxletterClickRate']
    tags:
      - name: dashboard.widget
        identifier: luxletterClickRate
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\UnsubscribeRateWidget:
    arguments: ['luxletterUnsubscribeRate']
    tags:
      - name: dashboard.widget
        identifier: luxletterUnsubscribeRate
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\ReceiverWidget:
    arguments: ['luxletterReceiver']
    tags:
      - name: dashboard.widget
        identifier: luxletterReceiver
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\NewsletterWidget:
    arguments: ['luxletterNewsletter']
    tags:
      - name: dashboard.widget
        identifier: luxletterNewsletter
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\LastNewslettersOpenRateWidget:
    arguments: ['luxletterLastNewslettersOpenRate']
    tags:
      - name: dashboard.widget
        identifier: luxletterLastNewslettersOpenRate
        widgetGroups: 'luxletter'

  In2code\Luxletter\Widget\LastNewslettersClickRateWidget:
    arguments: ['luxletterLastNewslettersClickRate']
    tags:
      - name: dashboard.widget
        identifier: luxletterLastNewslettersClickRate
        widgetGroups: 'luxletter'
